## Tensors

Tensors are the key data structure in PyTorch. Think of them like NumPy’s ndarrays. However, Tensors have added properties that we shall look into later that make them ideal for Deep Learning Computations i.e run on GPUs, support for autograd.

Lets play around with tensors. First you should import pytorch

In [1]:
# command to show all printouts in each cell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
# Import required modules
import torch
import numpy as np

#### Creating Tensors

In [3]:
# From existing data - i.e. from a python list
x = [[1, 2], [3, 4]]
tensor_x = torch.tensor(x)
tensor_x


tensor([[1, 2],
        [3, 4]])

In [4]:
# From a numpy array
array = np.array([[1, 2], [3, 4]])
tensor = torch.from_numpy(array)
tensor

tensor([[1, 2],
        [3, 4]])

In [5]:
# 1d tensor - directly
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [6]:
# Other functions to Initialise tensors. Try all of them

#torch.zeros(4, 6) # Initialize with zeros
# torch.ones(4,6) # Initialise with ones
rnd_tensor = torch.rand(4,6) # Samples from the uniform distribution
rnd_tensor.dtype
# torch.randn(4,6) # Samples from Gaussian  distribition

torch.float32

#### Tensor Attributes

In [7]:
# Accessing a tensor's shape (the length along each axis) by inspecting its shape property.
x.shape

torch.Size([12])

In [8]:
# Data type
x.dtype

torch.float32

In [9]:
!nvidia-smi

Tue Mar 26 16:36:59 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   45C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [10]:
x.device
torch.cuda.is_available()
torch.cuda.device_count()
torch.cuda.current_device()
torch.cuda.device(0)
torch.cuda.get_device_name(0)

device(type='cpu')

True

1

0

'Tesla T4'

### Operations on Tensors

Like ndarrays, you can perform several operations on Tensors.

In [11]:
# Create 2  4x6 Matrix

a = torch.randn(4,6)
b = torch.rand(4, 6)
print(a)
print(b)
a.shape
b.shape

tensor([[ 0.0952,  0.1743, -1.5826, -0.8212,  0.7538,  0.3054],
        [ 0.9043,  0.3081,  0.3395,  1.4175,  0.3880,  0.4698],
        [ 0.6794, -0.7016,  0.0140,  0.1782,  0.0392, -0.5892],
        [ 1.4609,  0.0774,  0.5859,  0.2251,  0.7789, -1.1795]])
tensor([[0.6090, 0.3644, 0.6575, 0.2275, 0.2583, 0.6865],
        [0.8575, 0.6357, 0.9160, 0.9728, 0.0517, 0.2138],
        [0.3089, 0.7744, 0.5368, 0.2257, 0.1187, 0.4581],
        [0.3618, 0.8040, 0.8406, 0.9978, 0.1566, 0.9466]])


torch.Size([4, 6])

torch.Size([4, 6])

In [13]:
# set a device to gpu if available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

# generate a random data on cpu side and move it to the gpu
a1 = torch.randn(10)
print(a1)
a1.shape
a1_gpu = a1.to(device)
print(a1_gpu)

# generatie it directly on the gpu
a1_gpu_direct = torch.rand(10, device=device)
print(a1_gpu_direct)

# move the data back to the host
a1_cpu = a1_gpu_direct.cpu()
print(a1_cpu)


cuda
tensor([-0.4524, -1.6083,  0.3847, -0.6702,  0.5408,  1.1847, -0.9694, -0.9350,
         0.6679, -1.3234])


torch.Size([10])

tensor([-0.4524, -1.6083,  0.3847, -0.6702,  0.5408,  1.1847, -0.9694, -0.9350,
         0.6679, -1.3234], device='cuda:0')
tensor([0.5553, 0.1328, 0.8429, 0.0344, 0.2915, 0.3682, 0.9794, 0.4917, 0.0020,
        0.9197], device='cuda:0')
tensor([0.5553, 0.1328, 0.8429, 0.0344, 0.2915, 0.3682, 0.9794, 0.4917, 0.0020,
        0.9197])


In [14]:
# Concantenate (Try both dimensions )
big_tensor = torch.cat([a,b], dim=1)
print(big_tensor)
big_tensor.shape

tensor([[ 0.0952,  0.1743, -1.5826, -0.8212,  0.7538,  0.3054,  0.6090,  0.3644,
          0.6575,  0.2275,  0.2583,  0.6865],
        [ 0.9043,  0.3081,  0.3395,  1.4175,  0.3880,  0.4698,  0.8575,  0.6357,
          0.9160,  0.9728,  0.0517,  0.2138],
        [ 0.6794, -0.7016,  0.0140,  0.1782,  0.0392, -0.5892,  0.3089,  0.7744,
          0.5368,  0.2257,  0.1187,  0.4581],
        [ 1.4609,  0.0774,  0.5859,  0.2251,  0.7789, -1.1795,  0.3618,  0.8040,
          0.8406,  0.9978,  0.1566,  0.9466]])


torch.Size([4, 12])

In [ ]:
# Add
c = a + b
print(c)

tensor([[ 0.4612,  1.8117, -0.0500,  0.3011, -0.8156,  0.0563],
        [-0.1435,  1.2419,  0.5611,  0.6351,  1.0297,  0.6162],
        [ 1.8271,  0.7804, -0.2588,  1.0788, -0.3311, -0.0883],
        [ 2.3283,  0.7356,  0.5921, -0.3621,  0.3368,  1.7201]])


In [ ]:
torch.add(a,b)

tensor([[ 0.4612,  1.8117, -0.0500,  0.3011, -0.8156,  0.0563],
        [-0.1435,  1.2419,  0.5611,  0.6351,  1.0297,  0.6162],
        [ 1.8271,  0.7804, -0.2588,  1.0788, -0.3311, -0.0883],
        [ 2.3283,  0.7356,  0.5921, -0.3621,  0.3368,  1.7201]])

In [ ]:
a*b

tensor([[ 0.0441,  0.3012, -0.0809, -0.1430, -0.6181, -0.0352],
        [-0.7695,  0.2432,  0.0019,  0.0935,  0.1158,  0.0716],
        [ 0.8321,  0.1340, -0.4140,  0.2144, -0.6926, -0.3190],
        [ 1.2520,  0.0106, -0.0422, -0.1497,  0.0144,  0.2296]])

In [ ]:
# reshaping with view
c.view(8,3)

tensor([[-0.0845, -0.1748,  1.1645],
        [ 1.4174, -0.0552, -1.3394],
        [ 1.6061,  2.1778,  1.6685],
        [ 1.3083,  1.9782,  2.0632],
        [-0.8111,  1.0117,  1.1153],
        [ 2.0320, -0.1000,  0.1676],
        [ 1.3022,  1.9051, -0.7975],
        [ 1.1672,  0.0968, -1.1704]])

In [ ]:
# To change the shape of a tensor without altering either the number of elements or their values,
# invoke the reshape function.
c.reshape(8, 3)

tensor([[-0.0845, -0.1748,  1.1645],
        [ 1.4174, -0.0552, -1.3394],
        [ 1.6061,  2.1778,  1.6685],
        [ 1.3083,  1.9782,  2.0632],
        [-0.8111,  1.0117,  1.1153],
        [ 2.0320, -0.1000,  0.1676],
        [ 1.3022,  1.9051, -0.7975],
        [ 1.1672,  0.0968, -1.1704]])

***Pay attention to view(), we shall come back to it later***


***What do you think is the difference between view() and reshape() in Numpy ?***

***What is the data type of the tensors we created. Can you change data types of tensors ?***

In PyTorch, both the view and reshape methods are used to change the shape of a tensor, but there are subtle differences between them:

    view method:
        view is a method specific to PyTorch tensors.
        It returns a new view of the original tensor with the specified shape.
        It does not create a copy of the data; instead, it shares the underlying data with the original tensor.
        The new shape must be compatible with the number of elements in the original tensor. In other words, the total number of elements in the new shape must match the total number of elements in the original tensor.
        If the new shape cannot be achieved with the original tensor's data contiguous in memory, view will raise an error. In such cases, you can use reshape.

    reshape method:
        reshape is a method available in both NumPy and PyTorch.
        It returns a new tensor with the specified shape.
        Like view, it does not create a copy of the data by default; instead, it shares the underlying data with the original tensor.
        It allows reshaping the tensor even when the new shape cannot be achieved with the original tensor's data contiguous in memory. In such cases, it will create a copy of the data.
        In PyTorch, you can specify copy=True to ensure a copy of the data is made when reshaping.

In [ ]:
# Create a tensor
a_tensor = torch.arange(12)

# Using view method
view_tensor = a_tensor.view(3, 4)

# Using view method - not compatible view
#view_tensor = a_tensor.view(3, 8)

# Using reshape method
reshape_tensor = a_tensor.reshape(3, 4)

# Using reshape method - not compatible shape - rise error
#reshape_tensor1 = a_tensor.reshape(3, 8)

# Modify the original tensor
a_tensor[0] = 100

# Print the tensors
print("Original Tensor:")
print(a_tensor)
print("\nView Tensor:")
print(view_tensor)
print("\nReshape Tensor:")
print(reshape_tensor)

Original Tensor:
tensor([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

View Tensor:
tensor([[100,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]])

Reshape Tensor:
tensor([[100,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]])
